MVCMusicStore2019/Controllers/AdminRoleController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using MVCMusicStore2019.Infrastructure;
using MVCMusicStore2019.Models;
using MVCMusicStore2019.ViewModels;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace MVCMusicStore2019.Controllers
{
    //[Authorize(Roles = "Administrators")]
    public class AdminRoleController: Controller
    {
        public ActionResult Index()
        {
            return View(RoleManager.Roles);
        }
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Create([Required]string name)
        {
            if (ModelState.IsValid)
            {
                IdentityResult result = await RoleManager.CreateAsync(new ApplicationRole(name));
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    AddErrorsFromResult(result);
                }
            }
            return View(name);
        }

        [HttpPost]
        public async Task<ActionResult> Delete(string id)
        {
            ApplicationRole role = await RoleManager.FindByIdAsync(id);
            if (role != null)
            {
                IdentityResult result = await RoleManager.DeleteAsync(role);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    return View("Error", result.Errors);
                }
            }
            else
            {
                return View("Error", new string[] { "没有相关角色定义。" });
            }
        }
        public async Task<ActionResult> Edit(string id)
        {
            ApplicationRole role = await RoleManager.FindByIdAsync(id);
            string[] memberIDs = role.Users.Select(x => x.UserId).ToArray();
            IEnumerable<ApplicationUser> members = UserManager.Users.Where(x => memberIDs.Any(y => y == x.Id));
            IEnumerable<ApplicationUser> nonMembers = UserManager.Users.Except(members);
            return View(new AdminEditRoleViewModel
            {
                Role = role,
                Members = members,
                NonMembers = nonMembers
            });
        }

        [HttpPost]
        public async Task<ActionResult> Edit(AdminModificationRoleModel model)
        {
            IdentityResult result;
            if (ModelState.IsValid)
            {
                foreach (string userId in model.IdsToAdd ?? new string[] { })
                {
                    result = await UserManager.AddToRoleAsync(userId, model.RoleName);
                    if (!result.Succeeded)
                    {
                        return View("Error", result.Errors);
                    }
                }
                foreach (string userId in model.IdsToDelete ?? new string[] { })
                {
                    result = await UserManager.RemoveFromRoleAsync(userId,
                       model.RoleName);
                    if (!result.Succeeded)
                    {
                        return View("Error", result.Errors);
                    }
                }
                return RedirectToAction("Index");
            }
            return View("Error", new string[] { "Role Not Found" });
        }
        private void AddErrorsFromResult(IdentityResult result)
        {
            foreach (string error in result.Errors)
            {
                ModelState.AddModelError("", error);
            }
        }

        private ApplicationUserManager UserManager
        {
            get
            {
                return HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
        }

        private ApplicationRoleManager RoleManager
        {
            get
            {
                return HttpContext.GetOwinContext().GetUserManager<ApplicationRoleManager>();
            }
        }
    }
}

MVCMusicStore2019/Controllers/AdminUserController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using MVCMusicStore2019.Infrastructure;
using MVCMusicStore2019.Models;
using MVCMusicStore2019.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace MVCMusicStore2019.Controllers
{
    //[Authorize(Roles = "Administrators")]
    public class AdminUserController : Controller
    {
        public ActionResult Index()
        {
            return View(UserManager.Users);
        }

        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<ActionResult> Create(AdminCreateUserViewModel model)
        {
            //用ModelState.IsValid属性检查所接收到的数据是否包含了我所需要的数据，
            //如果是，便创建一个AppUser类的新实例，并将它传递给UserManager.CreateAsync方法
            //使用异步的Identity方法让你的动作方法能够异步执行，这可以从整体上改善应用程序。
            if (ModelState.IsValid)
            {
                ApplicationUser user = new ApplicationUser { UserName = model.Name, Email = model.Email };
                IdentityResult result = await UserManager.CreateAsync(user, model.Password);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    AddErrorsFromResult(result);
                }
            }
            return View(model);
        }
        public async Task<ActionResult> Edit(string id)
        {
            ApplicationUser user = await UserManager.FindByIdAsync(id);
            AdminEditUserViewModel userEditVM = new AdminEditUserViewModel(user);
            if (user != null)
            {
                //return View(user);
                return View(userEditVM);
            }
            else
            {
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public async Task<ActionResult> Edit(string id, string email, string password)
        {
            ApplicationUser user = await UserManager.FindByIdAsync(id);
            if (user != null)
            {
                user.Email = email;
                //执行验证之前必须修改Email属性的值，因为ValidateAsync方法只接受用户类的实例
                IdentityResult validEmail = await UserManager.UserValidator.ValidateAsync(user);
                if (!validEmail.Succeeded)
                {
                    AddErrorsFromResult(validEmail);
                }
                IdentityResult validPass = null;
                if (password != string.Empty)
                {
                    //和Email一样，执行验证之前必须修改Password属性的值，因为ValidateAsync方法只接受用户类的实例
                    validPass = await UserManager.PasswordValidator.ValidateAsync(password);
                    if (validPass.Succeeded)
                    {
                        //由于存储到DB中的pw是Hash值（目的：防止口令被窃取），所以需要进行修改属性以完成Hash值得比对
                        //转换Hash值是通过IPasswordHasher接口实现
                        user.PasswordHash = UserManager.PasswordHasher.HashPassword(password);
                    }
                    else
                    {
                        AddErrorsFromResult(validPass);
                    }
                }
                // LINQ的使用技巧
                if ((validEmail.Succeeded && validPass == null) || (validEmail.Succeeded
                        && password != string.Empty && validPass.Succeeded))
                {
                    IdentityResult result = await UserManager.UpdateAsync(user);
                    if (result.Succeeded)
                    {
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        AddErrorsFromResult(result);
                    }
                }
            }
            else
            {
                ModelState.AddModelError("", "用户不存在。");
            }
            return View(user);
        }
        [HttpPost]
        public async Task<ActionResult> Delete(string id)
        {
            ApplicationUser user = await UserManager.FindByIdAsync(id);
            if (user != null)
            {
                IdentityResult result = await UserManager.DeleteAsync(user);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    return View("Error", result.Errors);
                }
            }
            else
            {
                return View("Error", new string[] { "用户不存在" });
            }
        }
        private void AddErrorsFromResult(IdentityResult result)
        {
            foreach (string error in result.Errors)
            {
                ModelState.AddModelError("", error);
            }
        }
        private ApplicationUserManager UserManager
        {
            get
            {
                return HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
        }
    }
}

MVCMusicStore2019/Views/AdminRole/Create.cshtml
@model string
@{
    ViewBag.Title = "新建角色";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@Html.ValidationSummary(false)
@using (Html.BeginForm())
{
    <div class="form-group">
        <label>Name</label>
        <input name="name" value="@Model" class="form-control" />
    </div>
    <button type="submit" class="btn btn-primary">新建</button>
    @Html.ActionLink("取消", "Index", null, new { @class = "btn btn-default" })
}

MVCMusicStore2019/Views/AdminRole/Edit.cshtml
@using MVCMusicStore2019.ViewModels
@model AdminEditRoleViewModel

@{
    ViewBag.Title = "Edit Role";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@Html.ValidationSummary()
@using (Html.BeginForm())
{
    <input type="hidden" name="roleName" value="@Model.Role.Name" />
    <div class="panel panel-primary">
        <div class="panel-heading">添加到 @Model.Role.Name</div>
        <table class="table table-striped">
            @if (Model.NonMembers.Count() == 0)
            {
                <tr><td colspan="2">所有用户都是Members。</td></tr>
            }
            else
            {
                <tr><td>用户ID</td><td>添加到角色</td></tr>
                foreach (MVCMusicStore2019.Models.ApplicationUser user in Model.NonMembers)
                {
                    <tr>
                        <td>@user.UserName</td>
                        <td>
                            <input type="checkbox" name="IdsToAdd" value="@user.Id">
                        </td>
                    </tr>
                }
            }
        </table>
    </div>
    <div class="panel panel-primary">
        <div class="panel-heading">从 @Model.Role.Name 组移除</div>
        <table class="table table-striped">
            @if (Model.Members.Count() == 0)
            {
                <tr><td colspan="2">该角色没有用户</td></tr>
            }
            else
            {
                <tr><td>用户ID</td><td>从角色移除</td></tr>
                foreach (MVCMusicStore2019.Models.ApplicationUser user in Model.Members)
                {
                    <tr>
                        <td>@user.UserName</td>
                        <td>
                            <input type="checkbox" name="IdsToDelete" value="@user.Id">
                        </td>
                    </tr>
                }
            }
        </table>
    </div>
    <button type="submit" class="btn btn-primary">保存</button>
    @Html.ActionLink("取消", "Index", null, new { @class = "btn btn-default" })
}

MVCMusicStore2019/Views/AdminRole/Index.cshtml
@using MVCMusicStore2019.Models
@using MVCMusicStore2019.Infrastructure
@model IEnumerable<ApplicationRole>

@{
    ViewBag.Title = "系统角色";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>


<div class="panel panel-primary">
    <div class="panel-heading">Roles——系统用户角色列表</div>
    <table class="table table-striped">

        <tr>
            <th>用户ID</th>            
            <th>用户名</th>
            <th>角色</th>
            <th></th>
        </tr>
        @if (Model.Count() == 0)
        {
            <tr><td colspan="4" class="text-center">没有角色列表数据</td></tr>
        }
        else
        {
            foreach (ApplicationRole role in Model)
            {
                <tr>
                    <td>@role.Id</td>
                    <td>@role.Name</td>
                    <td>
                        @if (role.Users == null || role.Users.Count == 0)
                        {
                            @: 该角色组没有用户
                        }
                        else
                        {
                            <p>
                                @string.Join(", ", role.Users.Select(x =>Html.GetUserName(x.UserId)))
                        </p>
                        }
                    </td>
                    <td>
                        @using (Html.BeginForm("Delete", "AdminRole",
                        new { id = role.Id }))
                        {
                            @Html.ActionLink("编辑", "Edit", new { id = role.Id },
                                     new { @class = "btn btn-primary btn-xs" })
                            <button class="btn btn-danger btn-xs" type="submit">
                                删除
                            </button>
                        }
                    </td>
                </tr>
            }
        }
    </table>
</div>
@Html.ActionLink("新建", "Create", null, new { @class = "btn btn-primary" })  
@Html.ActionLink("取消", "Index", "Home", null, new { @class = "btn btn-default" })
@Html.ActionLink("用户管理", "Index", "AdminUser", null, new { @class = "btn btn-primary" }) 