MusicStore/MVCMusicStore2019/Controllers/MusicStoreIndexController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVCMusicStore2019.Models;
using MVCMusicStore2019.Repository;
using MVCMusicStore2019.Models.MusicStore;
using MVCMusicStore2019.ViewModels;

namespace MVCMusicStore2019.Controllers
{
    public class MusicStoreIndexController : Controller
    {
        // GET: MusicStoreIndex
        private readonly IEntityRepository<Album> _Service;
        private readonly IEntityRepository<PopularHotList> _phlService;
        public MusicStoreIndexController(IEntityRepository<Album> service, IEntityRepository<PopularHotList> phlService)
        {
            this._Service = service;
            this._phlService = phlService;
        }
       
        public JsonResult GetPics()
        {
            var entityList = _Service.GetAll();//获取Album所有的数据
            var picList = entityList
                .OrderByDescending(x => x.IssueDate)//按出品日期倒序排序
                .Select(y => y.Urlstring)//选择UrlString一列数据
                .Skip(0)//从结果的第0条
                .Take(5)//取5条数据
                .ToList();
            return Json(picList);
        }
        /// <summary>
        /// 获取album表中的ID，Name，Price，URLsting
        /// 根据发行日期倒序排序
        /// </summary>
        /// <returns></returns>

        public JsonResult GetMusicStoreAlbums()
        {
            var entityList = _Service.GetAll().ToList();
            var jsonResult = entityList
                .OrderByDescending(x => x.IssueDate)//发行日期倒序排序
                .Select(result => new//使用集合索引器方式选择目标列
                {
                    result.ID,
                    result.Name,
                    result.Price,
                    result.Urlstring
                })
                .Skip(0).Take(10)//取1~10条数据
                .ToList();
            return Json(jsonResult);
        }
        public ActionResult  Detail(Guid id)
        {
            var entity = _Service.GetAll().Single(x => x.ID == id);
            AlbumViewModel vm = new AlbumViewModel(entity);
            return View(vm);
        }
        public ActionResult Index()
        {
            var boCollection = _Service.GetAll().OrderBy(x => x.Name);
            var vmCollection = new List<AlbumViewModel>();
            var count = 0;
            foreach (var item in boCollection)
            {
                var vm = new AlbumViewModel();
                vm.MapToModel(item);
                vm.OrderNumber = (++count).ToString();
                vmCollection.Add(vm);
            }
            ViewBag.Title = "专辑";
            return View(vmCollection);
        }
        public JsonResult AddCTR(Guid id)
        {
            var result = false;
            var entity = _phlService.GetSingleById(id);
            if(entity==null)
            {
                PopularHotList bo = new PopularHotList();
                bo.ID = id;
                bo.Album = _phlService.GetSingleReleVvance<Album>(id);
                bo.AlbumID = id;
                bo.CTR += 1;
                _phlService.AddAndSave(bo);
                result = true;
            }
            else
            {
                 entity.CTR += 1;
                _phlService.Edit(entity);
                result = true;
            }
            return Json(result); 
        }
    }
}

MusicStore/MVCMusicStore2019/Views/MusicStoreIndex/Index.cshtml
@model IEnumerable<MVCMusicStore2019.ViewModels.AlbumViewModel>
@{
    ViewBag.Title = "音乐专辑页面";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>系统管理员 @ViewBag.Title 管理页面</h2>
<div class="panel panel-primary">
    <div class="panel-heading">
        @ViewBag.Title 列表
    </div>
    <table class="table table-striped">
        <tr>
            <th>@Html.DisplayNameFor(model => model.OrderNumber)</th>
            <th>@Html.DisplayNameFor(model => model.Urlstring)</th>
            <th>@Html.DisplayNameFor(model => model.Name)</th>
            <th>@Html.DisplayNameFor(model => model.Description)</th>
            <th>@Html.DisplayNameFor(model => model.Price)</th>
            <th>@Html.DisplayNameFor(model => model.IssueDate)</th>
        </tr>
        @using (Ajax.BeginForm("Index", new AjaxOptions()))
        {
            if (Model.Count() == 0 || Model == null)
            {
                <tr><td colspan="6" class="text-center">没有专辑数据</td></tr>
            }
            foreach (var item in Model)
            {
                <tr>
                    @Html.HiddenFor(modelItem => item.ID)
                    <th>@item.OrderNumber</th>
                    <td><img src="~/PICS/@Html.DisplayFor(modelItem => item.Urlstring)" style="width:65px" /></td>
                    <td>@Html.DisplayFor(modelItem => item.Name)</td>
                    <td>@Html.DisplayFor(modelItem => item.Description)</td>
                    <td>@Html.DisplayFor(modelItem => item.Price)</td>
                    <td>@Html.DisplayFor(modelItem => item.IssueDate)</td>
                    <td>
                       @{ 
                           var ajaxOptions = new AjaxOptions()
                           {
                               HttpMethod = "post",
                               UpdateTargetId = "renderBody",
                               InsertionMode = InsertionMode.Replace,
                               LoadingElementId = "loding",
                               LoadingElementDuration = 2000
                           };
                       }
                        @Ajax.ActionLink("点赞","AddCTR", "MusicStoreIndex", new { id = item.ID },ajaxOptions, new { @class= "btn  btn-xs glyphicon glyphicon-thumbs-up", @title = "点赞" })
                    </td>
                    <td>
                        @using (Html.BeginForm("TryListening", " MusicStoreIndex", new { id = item.ID }))
                        {
                            @Html.ActionLink("¥", "CheckOut", "Order", new { id = item.ID, price = item.Price },
                              new { @class = "btn btn-danger btn-xs ", @title = "购买" })
                            @Html.ActionLink(" ", "Details", new { id = item.ID, price = item.Price },
                            new { @class = "btn btn-primary btn-xs glyphicon glyphicon-shopping-cart", @title = "加入购物车"})
                            <button class="btn btn-success btn-xs"  type="submit">
                                <span class="glyphicon glyphicon-headphones" title="试听"></span>
                            </button>
                        }
                    </td>
                </tr>
            }
        }
    </table>
</div>
@Scripts.Render("~/bundles/jquery")
<script src="~/Scripts/MusicStore/MusicHome.js"></script>